# Generated by Django 4.0.3 on 2022-06-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                ("schema_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                (
                    "column_separator",
                    models.CharField(
                        choices=[
                            ("Comma", "Comma(,)"),
                            ("Semicolon", "Semicolon(;)"),
                            ("Tab", "Tab(/t)"),
                            ("Space", "Space( )"),
                            ("Pipe", "Pipe (|)"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                ("column_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full Name", "Full Name"),
                            ("Job", "Job"),
                            ("Email", "Email"),
                            ("Domain name", "Domain name"),
                            ("Phone number", "Phone number"),
                            ("Company name", "Company name"),
                            ("Text", "Text"),
                            ("Integer", "Integer"),
                            ("Address", "Address"),
                            ("Date", "Date"),
                        ],
                        max_length=30,
                    ),
                ),
                ("from_range", models.IntegerField(blank=True, null=True)),
                ("to_range", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csv_generator.schema",
                    ),
                ),
            ],
        ),
    ]
