# Generated by Django 4.0.3 on 2022-06-26 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csv_generator", "0002_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="last_modified",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
